name: Fetch key from Github

on: [push]
    
jobs:
  testaus:
    runs-on: ubuntu-latest

    env:
        MOVIE_API_KEY: ${{secrets.MOVIE_API_KEY}}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Asenna riippuvuudet
        run: npm install
      
      - name: Aja testit avaimella
        run: npm run test

      
